{
 "title": "Gateway Detail",
 "tags": [
  "microservices",
  "gateway"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Gateway Performance", "type": "row", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Rate (QPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"gateway\"}[1m])) by (path, method)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "95th Percentile Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"gateway\"}[1m])) by (le, path))",
     "legendFormat": "P95 {{path}}"
    }
   ]
  },
  {
   "title": "Responses by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"gateway\"}[1m])) by (status)",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "Memory Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"gateway\"}",
     "legendFormat": "Allocated Bytes"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"gateway\"}",
     "legendFormat": "Goroutines"
    }
   ]
  }
 ]
}