// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: apps/restaurant-service/pb/restaurant.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestaurantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantResponse) Reset() {
	*x = RestaurantResponse{}
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantResponse) ProtoMessage() {}

func (x *RestaurantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantResponse.ProtoReflect.Descriptor instead.
func (*RestaurantResponse) Descriptor() ([]byte, []int) {
	return file_apps_restaurant_service_pb_restaurant_proto_rawDescGZIP(), []int{0}
}

func (x *RestaurantResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RestaurantResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestaurantResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RestaurantResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RestaurantResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateRestaurantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRestaurantRequest) Reset() {
	*x = CreateRestaurantRequest{}
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRestaurantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRestaurantRequest) ProtoMessage() {}

func (x *CreateRestaurantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRestaurantRequest.ProtoReflect.Descriptor instead.
func (*CreateRestaurantRequest) Descriptor() ([]byte, []int) {
	return file_apps_restaurant_service_pb_restaurant_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRestaurantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRestaurantRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRestaurantRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type UpdateRestaurantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRestaurantRequest) Reset() {
	*x = UpdateRestaurantRequest{}
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRestaurantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRestaurantRequest) ProtoMessage() {}

func (x *UpdateRestaurantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRestaurantRequest.ProtoReflect.Descriptor instead.
func (*UpdateRestaurantRequest) Descriptor() ([]byte, []int) {
	return file_apps_restaurant_service_pb_restaurant_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRestaurantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRestaurantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRestaurantRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateRestaurantRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetRestaurantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRestaurantRequest) Reset() {
	*x = GetRestaurantRequest{}
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantRequest) ProtoMessage() {}

func (x *GetRestaurantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantRequest.ProtoReflect.Descriptor instead.
func (*GetRestaurantRequest) Descriptor() ([]byte, []int) {
	return file_apps_restaurant_service_pb_restaurant_proto_rawDescGZIP(), []int{3}
}

func (x *GetRestaurantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListRestaurantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRestaurantsRequest) Reset() {
	*x = ListRestaurantsRequest{}
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRestaurantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRestaurantsRequest) ProtoMessage() {}

func (x *ListRestaurantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRestaurantsRequest.ProtoReflect.Descriptor instead.
func (*ListRestaurantsRequest) Descriptor() ([]byte, []int) {
	return file_apps_restaurant_service_pb_restaurant_proto_rawDescGZIP(), []int{4}
}

type ListRestaurantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Restaurants   []*RestaurantResponse  `protobuf:"bytes,1,rep,name=restaurants,proto3" json:"restaurants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRestaurantsResponse) Reset() {
	*x = ListRestaurantsResponse{}
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRestaurantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRestaurantsResponse) ProtoMessage() {}

func (x *ListRestaurantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRestaurantsResponse.ProtoReflect.Descriptor instead.
func (*ListRestaurantsResponse) Descriptor() ([]byte, []int) {
	return file_apps_restaurant_service_pb_restaurant_proto_rawDescGZIP(), []int{5}
}

func (x *ListRestaurantsResponse) GetRestaurants() []*RestaurantResponse {
	if x != nil {
		return x.Restaurants
	}
	return nil
}

type CategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RestaurantId  string                 `protobuf:"bytes,2,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryResponse) Reset() {
	*x = CategoryResponse{}
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryResponse) ProtoMessage() {}

func (x *CategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryResponse.ProtoReflect.Descriptor instead.
func (*CategoryResponse) Descriptor() ([]byte, []int) {
	return file_apps_restaurant_service_pb_restaurant_proto_rawDescGZIP(), []int{6}
}

func (x *CategoryResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CategoryResponse) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *CategoryResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_apps_restaurant_service_pb_restaurant_proto_rawDescGZIP(), []int{7}
}

func (x *CreateCategoryRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *CreateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_apps_restaurant_service_pb_restaurant_proto_rawDescGZIP(), []int{8}
}

func (x *ListCategoriesRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*CategoryResponse    `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_apps_restaurant_service_pb_restaurant_proto_rawDescGZIP(), []int{9}
}

func (x *ListCategoriesResponse) GetCategories() []*CategoryResponse {
	if x != nil {
		return x.Categories
	}
	return nil
}

type MenuItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId    string                 `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Available     bool                   `protobuf:"varint,6,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItemResponse) Reset() {
	*x = MenuItemResponse{}
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItemResponse) ProtoMessage() {}

func (x *MenuItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItemResponse.ProtoReflect.Descriptor instead.
func (*MenuItemResponse) Descriptor() ([]byte, []int) {
	return file_apps_restaurant_service_pb_restaurant_proto_rawDescGZIP(), []int{10}
}

func (x *MenuItemResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MenuItemResponse) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *MenuItemResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuItemResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MenuItemResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MenuItemResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type CreateMenuItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMenuItemRequest) Reset() {
	*x = CreateMenuItemRequest{}
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMenuItemRequest) ProtoMessage() {}

func (x *CreateMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMenuItemRequest.ProtoReflect.Descriptor instead.
func (*CreateMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_apps_restaurant_service_pb_restaurant_proto_rawDescGZIP(), []int{11}
}

func (x *CreateMenuItemRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CreateMenuItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMenuItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMenuItemRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type UpdateMenuItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Available     bool                   `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMenuItemRequest) Reset() {
	*x = UpdateMenuItemRequest{}
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuItemRequest) ProtoMessage() {}

func (x *UpdateMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_apps_restaurant_service_pb_restaurant_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateMenuItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMenuItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMenuItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateMenuItemRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateMenuItemRequest) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type DeleteMenuItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMenuItemRequest) Reset() {
	*x = DeleteMenuItemRequest{}
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMenuItemRequest) ProtoMessage() {}

func (x *DeleteMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMenuItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_apps_restaurant_service_pb_restaurant_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteMenuItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMenuItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMenuItemResponse) Reset() {
	*x = DeleteMenuItemResponse{}
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMenuItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMenuItemResponse) ProtoMessage() {}

func (x *DeleteMenuItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMenuItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteMenuItemResponse) Descriptor() ([]byte, []int) {
	return file_apps_restaurant_service_pb_restaurant_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteMenuItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  string                 `protobuf:"bytes,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuRequest) Reset() {
	*x = GetMenuRequest{}
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuRequest) ProtoMessage() {}

func (x *GetMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuRequest.ProtoReflect.Descriptor instead.
func (*GetMenuRequest) Descriptor() ([]byte, []int) {
	return file_apps_restaurant_service_pb_restaurant_proto_rawDescGZIP(), []int{15}
}

func (x *GetMenuRequest) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

type GetMenuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MenuItemResponse    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuResponse) Reset() {
	*x = GetMenuResponse{}
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuResponse) ProtoMessage() {}

func (x *GetMenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuResponse.ProtoReflect.Descriptor instead.
func (*GetMenuResponse) Descriptor() ([]byte, []int) {
	return file_apps_restaurant_service_pb_restaurant_proto_rawDescGZIP(), []int{16}
}

func (x *GetMenuResponse) GetItems() []*MenuItemResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeleteRestaurantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRestaurantRequest) Reset() {
	*x = DeleteRestaurantRequest{}
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRestaurantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRestaurantRequest) ProtoMessage() {}

func (x *DeleteRestaurantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRestaurantRequest.ProtoReflect.Descriptor instead.
func (*DeleteRestaurantRequest) Descriptor() ([]byte, []int) {
	return file_apps_restaurant_service_pb_restaurant_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteRestaurantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRestaurantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRestaurantResponse) Reset() {
	*x = DeleteRestaurantResponse{}
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRestaurantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRestaurantResponse) ProtoMessage() {}

func (x *DeleteRestaurantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_restaurant_service_pb_restaurant_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRestaurantResponse.ProtoReflect.Descriptor instead.
func (*DeleteRestaurantResponse) Descriptor() ([]byte, []int) {
	return file_apps_restaurant_service_pb_restaurant_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteRestaurantResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_apps_restaurant_service_pb_restaurant_proto protoreflect.FileDescriptor

const file_apps_restaurant_service_pb_restaurant_proto_rawDesc = "" +
	"\n" +
	"+apps/restaurant-service/pb/restaurant.proto\x12\n" +
	"restaurant\"\x93\x01\n" +
	"\x12RestaurantResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"i\n" +
	"\x17CreateRestaurantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"y\n" +
	"\x17UpdateRestaurantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\"&\n" +
	"\x14GetRestaurantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16ListRestaurantsRequest\"[\n" +
	"\x17ListRestaurantsResponse\x12@\n" +
	"\vrestaurants\x18\x01 \x03(\v2\x1e.restaurant.RestaurantResponseR\vrestaurants\"[\n" +
	"\x10CategoryResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rrestaurant_id\x18\x02 \x01(\tR\frestaurantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"P\n" +
	"\x15CreateCategoryRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"<\n" +
	"\x15ListCategoriesRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\"V\n" +
	"\x16ListCategoriesResponse\x12<\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x1c.restaurant.CategoryResponseR\n" +
	"categories\"\xad\x01\n" +
	"\x10MenuItemResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\tR\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1c\n" +
	"\tavailable\x18\x06 \x01(\bR\tavailable\"\x84\x01\n" +
	"\x15CreateMenuItemRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\"\x91\x01\n" +
	"\x15UpdateMenuItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1c\n" +
	"\tavailable\x18\x05 \x01(\bR\tavailable\"'\n" +
	"\x15DeleteMenuItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeleteMenuItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x0eGetMenuRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\tR\frestaurantId\"E\n" +
	"\x0fGetMenuResponse\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.restaurant.MenuItemResponseR\x05items\")\n" +
	"\x17DeleteRestaurantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x18DeleteRestaurantResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xc2\a\n" +
	"\x11RestaurantService\x12W\n" +
	"\x10CreateRestaurant\x12#.restaurant.CreateRestaurantRequest\x1a\x1e.restaurant.RestaurantResponse\x12W\n" +
	"\x10UpdateRestaurant\x12#.restaurant.UpdateRestaurantRequest\x1a\x1e.restaurant.RestaurantResponse\x12Q\n" +
	"\rGetRestaurant\x12 .restaurant.GetRestaurantRequest\x1a\x1e.restaurant.RestaurantResponse\x12Z\n" +
	"\x0fListRestaurants\x12\".restaurant.ListRestaurantsRequest\x1a#.restaurant.ListRestaurantsResponse\x12]\n" +
	"\x10DeleteRestaurant\x12#.restaurant.DeleteRestaurantRequest\x1a$.restaurant.DeleteRestaurantResponse\x12Q\n" +
	"\x0eCreateCategory\x12!.restaurant.CreateCategoryRequest\x1a\x1c.restaurant.CategoryResponse\x12W\n" +
	"\x0eListCategories\x12!.restaurant.ListCategoriesRequest\x1a\".restaurant.ListCategoriesResponse\x12Q\n" +
	"\x0eCreateMenuItem\x12!.restaurant.CreateMenuItemRequest\x1a\x1c.restaurant.MenuItemResponse\x12Q\n" +
	"\x0eUpdateMenuItem\x12!.restaurant.UpdateMenuItemRequest\x1a\x1c.restaurant.MenuItemResponse\x12W\n" +
	"\x0eDeleteMenuItem\x12!.restaurant.DeleteMenuItemRequest\x1a\".restaurant.DeleteMenuItemResponse\x12B\n" +
	"\aGetMenu\x12\x1a.restaurant.GetMenuRequest\x1a\x1b.restaurant.GetMenuResponseB\x17Z\x15restaurant-service/pbb\x06proto3"

var (
	file_apps_restaurant_service_pb_restaurant_proto_rawDescOnce sync.Once
	file_apps_restaurant_service_pb_restaurant_proto_rawDescData []byte
)

func file_apps_restaurant_service_pb_restaurant_proto_rawDescGZIP() []byte {
	file_apps_restaurant_service_pb_restaurant_proto_rawDescOnce.Do(func() {
		file_apps_restaurant_service_pb_restaurant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_restaurant_service_pb_restaurant_proto_rawDesc), len(file_apps_restaurant_service_pb_restaurant_proto_rawDesc)))
	})
	return file_apps_restaurant_service_pb_restaurant_proto_rawDescData
}

var file_apps_restaurant_service_pb_restaurant_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_apps_restaurant_service_pb_restaurant_proto_goTypes = []any{
	(*RestaurantResponse)(nil),       // 0: restaurant.RestaurantResponse
	(*CreateRestaurantRequest)(nil),  // 1: restaurant.CreateRestaurantRequest
	(*UpdateRestaurantRequest)(nil),  // 2: restaurant.UpdateRestaurantRequest
	(*GetRestaurantRequest)(nil),     // 3: restaurant.GetRestaurantRequest
	(*ListRestaurantsRequest)(nil),   // 4: restaurant.ListRestaurantsRequest
	(*ListRestaurantsResponse)(nil),  // 5: restaurant.ListRestaurantsResponse
	(*CategoryResponse)(nil),         // 6: restaurant.CategoryResponse
	(*CreateCategoryRequest)(nil),    // 7: restaurant.CreateCategoryRequest
	(*ListCategoriesRequest)(nil),    // 8: restaurant.ListCategoriesRequest
	(*ListCategoriesResponse)(nil),   // 9: restaurant.ListCategoriesResponse
	(*MenuItemResponse)(nil),         // 10: restaurant.MenuItemResponse
	(*CreateMenuItemRequest)(nil),    // 11: restaurant.CreateMenuItemRequest
	(*UpdateMenuItemRequest)(nil),    // 12: restaurant.UpdateMenuItemRequest
	(*DeleteMenuItemRequest)(nil),    // 13: restaurant.DeleteMenuItemRequest
	(*DeleteMenuItemResponse)(nil),   // 14: restaurant.DeleteMenuItemResponse
	(*GetMenuRequest)(nil),           // 15: restaurant.GetMenuRequest
	(*GetMenuResponse)(nil),          // 16: restaurant.GetMenuResponse
	(*DeleteRestaurantRequest)(nil),  // 17: restaurant.DeleteRestaurantRequest
	(*DeleteRestaurantResponse)(nil), // 18: restaurant.DeleteRestaurantResponse
}
var file_apps_restaurant_service_pb_restaurant_proto_depIdxs = []int32{
	0,  // 0: restaurant.ListRestaurantsResponse.restaurants:type_name -> restaurant.RestaurantResponse
	6,  // 1: restaurant.ListCategoriesResponse.categories:type_name -> restaurant.CategoryResponse
	10, // 2: restaurant.GetMenuResponse.items:type_name -> restaurant.MenuItemResponse
	1,  // 3: restaurant.RestaurantService.CreateRestaurant:input_type -> restaurant.CreateRestaurantRequest
	2,  // 4: restaurant.RestaurantService.UpdateRestaurant:input_type -> restaurant.UpdateRestaurantRequest
	3,  // 5: restaurant.RestaurantService.GetRestaurant:input_type -> restaurant.GetRestaurantRequest
	4,  // 6: restaurant.RestaurantService.ListRestaurants:input_type -> restaurant.ListRestaurantsRequest
	17, // 7: restaurant.RestaurantService.DeleteRestaurant:input_type -> restaurant.DeleteRestaurantRequest
	7,  // 8: restaurant.RestaurantService.CreateCategory:input_type -> restaurant.CreateCategoryRequest
	8,  // 9: restaurant.RestaurantService.ListCategories:input_type -> restaurant.ListCategoriesRequest
	11, // 10: restaurant.RestaurantService.CreateMenuItem:input_type -> restaurant.CreateMenuItemRequest
	12, // 11: restaurant.RestaurantService.UpdateMenuItem:input_type -> restaurant.UpdateMenuItemRequest
	13, // 12: restaurant.RestaurantService.DeleteMenuItem:input_type -> restaurant.DeleteMenuItemRequest
	15, // 13: restaurant.RestaurantService.GetMenu:input_type -> restaurant.GetMenuRequest
	0,  // 14: restaurant.RestaurantService.CreateRestaurant:output_type -> restaurant.RestaurantResponse
	0,  // 15: restaurant.RestaurantService.UpdateRestaurant:output_type -> restaurant.RestaurantResponse
	0,  // 16: restaurant.RestaurantService.GetRestaurant:output_type -> restaurant.RestaurantResponse
	5,  // 17: restaurant.RestaurantService.ListRestaurants:output_type -> restaurant.ListRestaurantsResponse
	18, // 18: restaurant.RestaurantService.DeleteRestaurant:output_type -> restaurant.DeleteRestaurantResponse
	6,  // 19: restaurant.RestaurantService.CreateCategory:output_type -> restaurant.CategoryResponse
	9,  // 20: restaurant.RestaurantService.ListCategories:output_type -> restaurant.ListCategoriesResponse
	10, // 21: restaurant.RestaurantService.CreateMenuItem:output_type -> restaurant.MenuItemResponse
	10, // 22: restaurant.RestaurantService.UpdateMenuItem:output_type -> restaurant.MenuItemResponse
	14, // 23: restaurant.RestaurantService.DeleteMenuItem:output_type -> restaurant.DeleteMenuItemResponse
	16, // 24: restaurant.RestaurantService.GetMenu:output_type -> restaurant.GetMenuResponse
	14, // [14:25] is the sub-list for method output_type
	3,  // [3:14] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_apps_restaurant_service_pb_restaurant_proto_init() }
func file_apps_restaurant_service_pb_restaurant_proto_init() {
	if File_apps_restaurant_service_pb_restaurant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_restaurant_service_pb_restaurant_proto_rawDesc), len(file_apps_restaurant_service_pb_restaurant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_restaurant_service_pb_restaurant_proto_goTypes,
		DependencyIndexes: file_apps_restaurant_service_pb_restaurant_proto_depIdxs,
		MessageInfos:      file_apps_restaurant_service_pb_restaurant_proto_msgTypes,
	}.Build()
	File_apps_restaurant_service_pb_restaurant_proto = out.File
	file_apps_restaurant_service_pb_restaurant_proto_goTypes = nil
	file_apps_restaurant_service_pb_restaurant_proto_depIdxs = nil
}
