// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: apps/analytics-service/pb/analytics.proto

package analyticspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetKPIsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKPIsRequest) Reset() {
	*x = GetKPIsRequest{}
	mi := &file_apps_analytics_service_pb_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKPIsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKPIsRequest) ProtoMessage() {}

func (x *GetKPIsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_analytics_service_pb_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKPIsRequest.ProtoReflect.Descriptor instead.
func (*GetKPIsRequest) Descriptor() ([]byte, []int) {
	return file_apps_analytics_service_pb_analytics_proto_rawDescGZIP(), []int{0}
}

type GetKPIsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TotalOrders          int64                  `protobuf:"varint,1,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	TotalRevenue         float64                `protobuf:"fixed64,2,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	TotalDeliveredOrders int64                  `protobuf:"varint,3,opt,name=total_delivered_orders,json=totalDeliveredOrders,proto3" json:"total_delivered_orders,omitempty"`
	TotalCancelledOrders int64                  `protobuf:"varint,4,opt,name=total_cancelled_orders,json=totalCancelledOrders,proto3" json:"total_cancelled_orders,omitempty"`
	PaymentSuccessRate   float64                `protobuf:"fixed64,5,opt,name=payment_success_rate,json=paymentSuccessRate,proto3" json:"payment_success_rate,omitempty"`
	AvgDeliverySeconds   float64                `protobuf:"fixed64,6,opt,name=avg_delivery_seconds,json=avgDeliverySeconds,proto3" json:"avg_delivery_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetKPIsResponse) Reset() {
	*x = GetKPIsResponse{}
	mi := &file_apps_analytics_service_pb_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKPIsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKPIsResponse) ProtoMessage() {}

func (x *GetKPIsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_analytics_service_pb_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKPIsResponse.ProtoReflect.Descriptor instead.
func (*GetKPIsResponse) Descriptor() ([]byte, []int) {
	return file_apps_analytics_service_pb_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *GetKPIsResponse) GetTotalOrders() int64 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

func (x *GetKPIsResponse) GetTotalRevenue() float64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *GetKPIsResponse) GetTotalDeliveredOrders() int64 {
	if x != nil {
		return x.TotalDeliveredOrders
	}
	return 0
}

func (x *GetKPIsResponse) GetTotalCancelledOrders() int64 {
	if x != nil {
		return x.TotalCancelledOrders
	}
	return 0
}

func (x *GetKPIsResponse) GetPaymentSuccessRate() float64 {
	if x != nil {
		return x.PaymentSuccessRate
	}
	return 0
}

func (x *GetKPIsResponse) GetAvgDeliverySeconds() float64 {
	if x != nil {
		return x.AvgDeliverySeconds
	}
	return 0
}

var File_apps_analytics_service_pb_analytics_proto protoreflect.FileDescriptor

const file_apps_analytics_service_pb_analytics_proto_rawDesc = "" +
	"\n" +
	")apps/analytics-service/pb/analytics.proto\x12\tanalytics\"\x10\n" +
	"\x0eGetKPIsRequest\"\xa9\x02\n" +
	"\x0fGetKPIsResponse\x12!\n" +
	"\ftotal_orders\x18\x01 \x01(\x03R\vtotalOrders\x12#\n" +
	"\rtotal_revenue\x18\x02 \x01(\x01R\ftotalRevenue\x124\n" +
	"\x16total_delivered_orders\x18\x03 \x01(\x03R\x14totalDeliveredOrders\x124\n" +
	"\x16total_cancelled_orders\x18\x04 \x01(\x03R\x14totalCancelledOrders\x120\n" +
	"\x14payment_success_rate\x18\x05 \x01(\x01R\x12paymentSuccessRate\x120\n" +
	"\x14avg_delivery_seconds\x18\x06 \x01(\x01R\x12avgDeliverySeconds2T\n" +
	"\x10AnalyticsService\x12@\n" +
	"\aGetKPIs\x12\x19.analytics.GetKPIsRequest\x1a\x1a.analytics.GetKPIsResponseB\"Z analytics-service/pb;analyticspbb\x06proto3"

var (
	file_apps_analytics_service_pb_analytics_proto_rawDescOnce sync.Once
	file_apps_analytics_service_pb_analytics_proto_rawDescData []byte
)

func file_apps_analytics_service_pb_analytics_proto_rawDescGZIP() []byte {
	file_apps_analytics_service_pb_analytics_proto_rawDescOnce.Do(func() {
		file_apps_analytics_service_pb_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_analytics_service_pb_analytics_proto_rawDesc), len(file_apps_analytics_service_pb_analytics_proto_rawDesc)))
	})
	return file_apps_analytics_service_pb_analytics_proto_rawDescData
}

var file_apps_analytics_service_pb_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apps_analytics_service_pb_analytics_proto_goTypes = []any{
	(*GetKPIsRequest)(nil),  // 0: analytics.GetKPIsRequest
	(*GetKPIsResponse)(nil), // 1: analytics.GetKPIsResponse
}
var file_apps_analytics_service_pb_analytics_proto_depIdxs = []int32{
	0, // 0: analytics.AnalyticsService.GetKPIs:input_type -> analytics.GetKPIsRequest
	1, // 1: analytics.AnalyticsService.GetKPIs:output_type -> analytics.GetKPIsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apps_analytics_service_pb_analytics_proto_init() }
func file_apps_analytics_service_pb_analytics_proto_init() {
	if File_apps_analytics_service_pb_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_analytics_service_pb_analytics_proto_rawDesc), len(file_apps_analytics_service_pb_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_analytics_service_pb_analytics_proto_goTypes,
		DependencyIndexes: file_apps_analytics_service_pb_analytics_proto_depIdxs,
		MessageInfos:      file_apps_analytics_service_pb_analytics_proto_msgTypes,
	}.Build()
	File_apps_analytics_service_pb_analytics_proto = out.File
	file_apps_analytics_service_pb_analytics_proto_goTypes = nil
	file_apps_analytics_service_pb_analytics_proto_depIdxs = nil
}
