// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: apps/search-service/pb/search.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_apps_search_service_pb_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_search_service_pb_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_apps_search_service_pb_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type RestaurantDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantDocument) Reset() {
	*x = RestaurantDocument{}
	mi := &file_apps_search_service_pb_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantDocument) ProtoMessage() {}

func (x *RestaurantDocument) ProtoReflect() protoreflect.Message {
	mi := &file_apps_search_service_pb_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantDocument.ProtoReflect.Descriptor instead.
func (*RestaurantDocument) Descriptor() ([]byte, []int) {
	return file_apps_search_service_pb_search_proto_rawDescGZIP(), []int{1}
}

func (x *RestaurantDocument) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RestaurantDocument) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestaurantDocument) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RestaurantDocument) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type SearchRestaurantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Restaurants   []*RestaurantDocument  `protobuf:"bytes,1,rep,name=restaurants,proto3" json:"restaurants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRestaurantsResponse) Reset() {
	*x = SearchRestaurantsResponse{}
	mi := &file_apps_search_service_pb_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRestaurantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRestaurantsResponse) ProtoMessage() {}

func (x *SearchRestaurantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_search_service_pb_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRestaurantsResponse.ProtoReflect.Descriptor instead.
func (*SearchRestaurantsResponse) Descriptor() ([]byte, []int) {
	return file_apps_search_service_pb_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRestaurantsResponse) GetRestaurants() []*RestaurantDocument {
	if x != nil {
		return x.Restaurants
	}
	return nil
}

type MenuDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RestaurantId  string                 `protobuf:"bytes,2,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	CategoryId    string                 `protobuf:"bytes,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	Available     bool                   `protobuf:"varint,7,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuDocument) Reset() {
	*x = MenuDocument{}
	mi := &file_apps_search_service_pb_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuDocument) ProtoMessage() {}

func (x *MenuDocument) ProtoReflect() protoreflect.Message {
	mi := &file_apps_search_service_pb_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuDocument.ProtoReflect.Descriptor instead.
func (*MenuDocument) Descriptor() ([]byte, []int) {
	return file_apps_search_service_pb_search_proto_rawDescGZIP(), []int{3}
}

func (x *MenuDocument) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MenuDocument) GetRestaurantId() string {
	if x != nil {
		return x.RestaurantId
	}
	return ""
}

func (x *MenuDocument) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *MenuDocument) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuDocument) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MenuDocument) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MenuDocument) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type SearchMenusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MenuDocument        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMenusResponse) Reset() {
	*x = SearchMenusResponse{}
	mi := &file_apps_search_service_pb_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMenusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMenusResponse) ProtoMessage() {}

func (x *SearchMenusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_search_service_pb_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMenusResponse.ProtoReflect.Descriptor instead.
func (*SearchMenusResponse) Descriptor() ([]byte, []int) {
	return file_apps_search_service_pb_search_proto_rawDescGZIP(), []int{4}
}

func (x *SearchMenusResponse) GetItems() []*MenuDocument {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_apps_search_service_pb_search_proto protoreflect.FileDescriptor

const file_apps_search_service_pb_search_proto_rawDesc = "" +
	"\n" +
	"#apps/search-service/pb/search.proto\x12\x06search\"%\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"t\n" +
	"\x12RestaurantDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\"Y\n" +
	"\x19SearchRestaurantsResponse\x12<\n" +
	"\vrestaurants\x18\x01 \x03(\v2\x1a.search.RestaurantDocumentR\vrestaurants\"\xce\x01\n" +
	"\fMenuDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rrestaurant_id\x18\x02 \x01(\tR\frestaurantId\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\tR\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x1c\n" +
	"\tavailable\x18\a \x01(\bR\tavailable\"A\n" +
	"\x13SearchMenusResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.search.MenuDocumentR\x05items2\xa1\x01\n" +
	"\rSearchService\x12M\n" +
	"\x11SearchRestaurants\x12\x15.search.SearchRequest\x1a!.search.SearchRestaurantsResponse\x12A\n" +
	"\vSearchMenus\x12\x15.search.SearchRequest\x1a\x1b.search.SearchMenusResponseB\x13Z\x11search-service/pbb\x06proto3"

var (
	file_apps_search_service_pb_search_proto_rawDescOnce sync.Once
	file_apps_search_service_pb_search_proto_rawDescData []byte
)

func file_apps_search_service_pb_search_proto_rawDescGZIP() []byte {
	file_apps_search_service_pb_search_proto_rawDescOnce.Do(func() {
		file_apps_search_service_pb_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_search_service_pb_search_proto_rawDesc), len(file_apps_search_service_pb_search_proto_rawDesc)))
	})
	return file_apps_search_service_pb_search_proto_rawDescData
}

var file_apps_search_service_pb_search_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_apps_search_service_pb_search_proto_goTypes = []any{
	(*SearchRequest)(nil),             // 0: search.SearchRequest
	(*RestaurantDocument)(nil),        // 1: search.RestaurantDocument
	(*SearchRestaurantsResponse)(nil), // 2: search.SearchRestaurantsResponse
	(*MenuDocument)(nil),              // 3: search.MenuDocument
	(*SearchMenusResponse)(nil),       // 4: search.SearchMenusResponse
}
var file_apps_search_service_pb_search_proto_depIdxs = []int32{
	1, // 0: search.SearchRestaurantsResponse.restaurants:type_name -> search.RestaurantDocument
	3, // 1: search.SearchMenusResponse.items:type_name -> search.MenuDocument
	0, // 2: search.SearchService.SearchRestaurants:input_type -> search.SearchRequest
	0, // 3: search.SearchService.SearchMenus:input_type -> search.SearchRequest
	2, // 4: search.SearchService.SearchRestaurants:output_type -> search.SearchRestaurantsResponse
	4, // 5: search.SearchService.SearchMenus:output_type -> search.SearchMenusResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_apps_search_service_pb_search_proto_init() }
func file_apps_search_service_pb_search_proto_init() {
	if File_apps_search_service_pb_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_search_service_pb_search_proto_rawDesc), len(file_apps_search_service_pb_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_search_service_pb_search_proto_goTypes,
		DependencyIndexes: file_apps_search_service_pb_search_proto_depIdxs,
		MessageInfos:      file_apps_search_service_pb_search_proto_msgTypes,
	}.Build()
	File_apps_search_service_pb_search_proto = out.File
	file_apps_search_service_pb_search_proto_goTypes = nil
	file_apps_search_service_pb_search_proto_depIdxs = nil
}
